ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS middle_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS fsr_id VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS education_institution VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS coach VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city_country VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS representative_phone VARCHAR(50);